apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook-b-dev
  namespace: argocd
spec:
  project: ops-central
  source:
    repoURL: https://github.com/gsl-meriemelouafi/kustomize-with-helm.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
